const Users = {

    CHECK_AUTH_API: 'CHECK_AUTH_API',

    LOGIN_USER_API: 'LOGIN_USER_API',

    LOGOUT_USER_API: 'LOGOUT_USER_API',

    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',

    UPDATE_LOGGED_IN_USER: 'UPDATE_LOGGED_IN_USER',

    UPDATE_USER_PROFILE_API: 'UPDATE_USER_PROFILE_API',

    GET_USER_CREDENTIALS_API: 'GET_USER_CREDENTIALS_API',

    UPDATE_USER_CREDENTIALS_API: 'UPDATE_USER_CREDENTIALS_API',

    UPDATE_USER_PASSWORD_API: 'UPDATE_USER_PASSWORD_API',

};

export default Users;
